/**
 * Projects Data — generated by Admin Studio on 2026-04-29T06:50:22.978Z
 */
const PROJECT_DATA = [
  {
    "id": "monticello",
    "title": "Monticello",
    "client": "Dheeraj Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2019,
    "img": "assets/Projects/monticello.jpg",
    "featured": true,
    "coordinates": [
      19.0596,
      72.8295
    ]
  },
  {
    "id": "del-sol",
    "title": "Del-Sol",
    "client": "Dheeraj Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2020,
    "img": "assets/Projects/Del Sol.jpg",
    "featured": false,
    "coordinates": [
      19.1136,
      72.8697
    ]
  },
  {
    "id": "insignia",
    "title": "Insignia",
    "client": "Dheeraj Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2018,
    "img": "assets/Projects/insignia.jpg",
    "featured": false,
    "coordinates": [
      19.065,
      72.835
    ]
  },
  {
    "id": "nafa",
    "title": "Nafa",
    "client": "Dheeraj Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2019,
    "img": null,
    "featured": false,
    "coordinates": [
      19.07,
      72.84
    ]
  },
  {
    "id": "tree-top",
    "title": "Tree Top",
    "client": "Lodha Group",
    "category": "residential",
    "location": "Mumbai",
    "area": "2.1L Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": "assets/Projects/Tree Top.jpg",
    "featured": true,
    "coordinates": [
      19.0178,
      72.8478
    ]
  },
  {
    "id": "splendora",
    "title": "Splendora",
    "client": "Lodha Group",
    "category": "residential",
    "location": "Thane",
    "area": "2.1L Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": "assets/Projects/selendora.jpg",
    "featured": false,
    "coordinates": [
      19.2667,
      72.9669
    ]
  },
  {
    "id": "luxaria",
    "title": "Luxaria",
    "client": "Lodha Group",
    "category": "residential",
    "location": "Thane",
    "area": "2.1L Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": "assets/Projects/luxaria lodha thane.jpg",
    "featured": false,
    "coordinates": [
      19.2183,
      72.9781
    ]
  },
  {
    "id": "seasons",
    "title": "Seasons",
    "client": "Rustomjee",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.8L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": "assets/Projects/seasons.jpg",
    "featured": false,
    "coordinates": [
      19.06,
      72.8777
    ]
  },
  {
    "id": "d-mart-vasai",
    "title": "D Mart Vasai",
    "client": "Avenue Supermarts",
    "category": "commercial",
    "location": "Vasai",
    "area": "40K Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": "assets/Projects/D mart vasai.jpg",
    "featured": false,
    "coordinates": [
      19.3919,
      72.8397
    ]
  },
  {
    "id": "time-square",
    "title": "Time Square",
    "client": "Ajmera Group",
    "category": "commercial",
    "location": "Mumbai",
    "area": "3.5L Sq.ft",
    "status": "completed",
    "year": 2020,
    "img": "assets/Projects/time square.jpg",
    "featured": true,
    "coordinates": [
      19.1197,
      72.8876
    ]
  },
  {
    "id": "krishna-raj",
    "title": "Krishna Raj",
    "client": "Rishi Kapoor",
    "category": "commercial",
    "location": "Mumbai",
    "area": "12K Sq.ft",
    "status": "completed",
    "year": 2018,
    "img": "assets/Projects/krishna raj.jpg",
    "featured": false,
    "coordinates": [
      19.0664,
      72.8322
    ]
  },
  {
    "id": "iris",
    "title": "Iris",
    "client": "Hiranandani",
    "category": "residential",
    "location": "Thane",
    "area": "2.0L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": "assets/Projects/iris.jpg",
    "featured": false,
    "coordinates": [
      19.2365,
      72.9723
    ]
  },
  {
    "id": "trafford",
    "title": "Trafford",
    "client": "Hiranandani",
    "category": "residential",
    "location": "Thane",
    "area": "2.0L Sq.ft",
    "status": "ongoing",
    "year": 2025,
    "img": null,
    "featured": false,
    "coordinates": [
      19.24,
      72.975
    ]
  },
  {
    "id": "bloomdale",
    "title": "Bloomdale",
    "client": "Mahindra Lifespaces",
    "category": "residential",
    "location": "Nagpur",
    "area": "5.0L Sq.ft",
    "status": "completed",
    "year": 2023,
    "img": "assets/Projects/bloomdale nagpur.jpg",
    "featured": true,
    "coordinates": [
      21.1458,
      79.0882
    ]
  },
  {
    "id": "ekta-trinity",
    "title": "Ekta Trinity",
    "client": "Ekta World",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.0L Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": "assets/Projects/ekta trinity.jpg",
    "featured": false,
    "coordinates": [
      19.0843,
      72.8358
    ]
  },
  {
    "id": "lake-riviera",
    "title": "Lake Riviera",
    "client": "Pashmina Realty",
    "category": "residential",
    "location": "Powai",
    "area": "3.1L Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": "assets/Projects/lake riviera.jpg",
    "featured": false,
    "coordinates": [
      19.1232,
      72.9096
    ]
  },
  {
    "id": "arkade-earth",
    "title": "Arkade Earth",
    "client": "Arkade Group",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.2L Sq.ft",
    "status": "completed",
    "year": 2023,
    "img": "assets/Projects/erkade earth.jpg",
    "featured": false,
    "coordinates": [
      19.135,
      72.935
    ]
  },
  {
    "id": "pavilion",
    "title": "Pavilion",
    "client": "K K Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "80K Sq.ft",
    "status": "completed",
    "year": 2020,
    "img": "assets/Projects/pavilion.jpg",
    "featured": false,
    "coordinates": [
      19.075,
      72.845
    ]
  },
  {
    "id": "ohana",
    "title": "Ohana",
    "client": "Ashok Gupta",
    "category": "residential",
    "location": "Mumbai",
    "area": "50K Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": null,
    "featured": false,
    "coordinates": [
      19.08,
      72.85
    ]
  },
  {
    "title": "BSUP",
    "id": "bsup",
    "client": "Kalyan Dombivali Municipal Corp.",
    "category": "infrastructure",
    "location": "Kalyan",
    "area": "5.5L Sq.ft",
    "img": "assets/Projects/Screenshot 2026-04-27 130156.png",
    "coordinates": [
      19.2437,
      73.1355
    ]
  },
  {
    "id": "bungalow-khandala",
    "title": "Bungalow Khandala",
    "client": "Dheeraj Realty",
    "category": "residential",
    "location": "Khandala",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2019,
    "img": null,
    "featured": false,
    "coordinates": [
      18.75,
      73.35
    ]
  },
  {
    "id": "antariksh-avalon",
    "title": "Antariksh Avalon",
    "client": "Antariksh Group",
    "category": "residential",
    "location": "Thane",
    "area": "1.5L Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": "assets/Projects/antriksh avalon.jpg",
    "featured": false,
    "coordinates": [
      19.2245,
      72.975
    ]
  },
  {
    "id": "pinez-teva",
    "title": "Pinez Teva",
    "client": "Ashok Gupta",
    "category": "residential",
    "location": "Mumbai",
    "area": "1.0L Sq.ft",
    "status": "completed",
    "year": 2020,
    "img": null,
    "featured": false,
    "coordinates": [
      19.085,
      72.855
    ]
  },
  {
    "id": "swagat-ashram",
    "title": "Swagat Ashram",
    "client": "Swagat Ashram Trust",
    "category": "residential",
    "location": "Mumbai",
    "area": "50K Sq.ft",
    "status": "completed",
    "year": 2019,
    "img": null,
    "featured": false,
    "coordinates": [
      19.09,
      72.86
    ]
  },
  {
    "id": "sands",
    "title": "Sands",
    "client": "Hiranandani",
    "category": "residential",
    "location": "Thane",
    "area": "1.8L Sq.ft",
    "status": "completed",
    "year": 2023,
    "img": null,
    "featured": false,
    "coordinates": [
      19.23,
      72.98
    ]
  },
  {
    "id": "t1",
    "title": "T1",
    "client": "Puraniks",
    "category": "residential",
    "location": "Thane",
    "area": "1.2L Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": null,
    "featured": false,
    "coordinates": [
      19.25,
      72.985
    ]
  },
  {
    "id": "conwood",
    "title": "Conwood",
    "client": "Enclave",
    "category": "residential",
    "location": "Mumbai",
    "area": "80K Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": "assets/Projects/Conwood Enclave.jpg",
    "featured": false,
    "coordinates": [
      19.095,
      72.865
    ]
  },
  {
    "id": "woodland",
    "title": "Woodland",
    "client": "Lokha",
    "category": "residential",
    "location": "Thane",
    "area": "1.0L Sq.ft",
    "status": "completed",
    "year": 2022,
    "img": null,
    "featured": false,
    "coordinates": [
      19.255,
      72.99
    ]
  },
  {
    "id": "sukrut",
    "title": "Sukrut",
    "client": "Tecno Realty",
    "category": "residential",
    "location": "Mumbai",
    "area": "60K Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": "assets/Projects/sukrut.jpg",
    "featured": false,
    "coordinates": [
      19.1,
      72.87
    ]
  },
  {
    "id": "ramkunj",
    "title": "Ramkunj",
    "client": "Mish & Mou",
    "category": "residential",
    "location": "Mumbai",
    "area": "40K Sq.ft",
    "status": "completed",
    "year": 2020,
    "img": null,
    "featured": false,
    "coordinates": [
      19.105,
      72.875
    ]
  },
  {
    "id": "holiday-home",
    "title": "Holiday Home",
    "client": "Private",
    "category": "residential",
    "location": "Goa",
    "area": "8K Sq.ft",
    "status": "completed",
    "year": 2021,
    "img": null,
    "featured": false,
    "coordinates": [
      15.2993,
      74.124
    ]
  },
  {
    "id": "marquee-avighna",
    "title": "Marquee",
    "client": "Avighna Group",
    "category": "residential",
    "location": "Worli",
    "area": "4L Sq.ft",
    "status": "ongoing",
    "year": 2023,
    "img": "assets/Projects/avighna.jpg",
    "featured": true,
    "coordinates": [
      19.0094,
      72.8163
    ]
  },
  {
    "id": "aakasha-techno",
    "title": "Aakasha",
    "client": "Techno Group",
    "category": "residential",
    "location": "Worli",
    "area": "3.5L Sq.ft",
    "status": "ongoing",
    "year": 2023,
    "img": "assets/Projects/AAKASA.jpg",
    "featured": false,
    "coordinates": [
      19.011,
      72.818
    ]
  },
  {
    "id": "stella-kherwadi",
    "title": "Stella Kherwadi",
    "client": "Rustomjee Group",
    "category": "residential",
    "location": "Bandra",
    "area": "2.2L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": "assets/Projects/Stella.jpg",
    "featured": false,
    "coordinates": [
      19.0596,
      72.831
    ]
  },
  {
    "id": "kismet-satguru",
    "title": "Kismet",
    "client": "JGB Builders LLP",
    "category": "residential",
    "location": "Bandra",
    "area": "1.7L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": "assets/Projects/kismet.jpg",
    "featured": false,
    "coordinates": [
      19.062,
      72.834
    ]
  },
  {
    "id": "alpha-ghatkopar",
    "title": "Alpha",
    "client": "Anntriksh Realtors Pvt. Ltd.",
    "category": "residential",
    "location": "Ghatkopar",
    "area": "2.6L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": "assets/Projects/antariksh-alpha.jpg",
    "featured": false,
    "coordinates": [
      19.086,
      72.9081
    ]
  },
  {
    "id": "sambhav-estate",
    "title": "Sambhav Estate",
    "client": "Mehta Developers Pvt. Ltd.",
    "category": "residential",
    "location": "Kemp's Corner",
    "area": "55K Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": null,
    "featured": false,
    "coordinates": [
      18.968,
      72.812
    ]
  },
  {
    "id": "casa-del-worli",
    "title": "Casa Del",
    "client": "Adishakti Associates",
    "category": "residential",
    "location": "Worli",
    "area": "1.92L Sq.ft",
    "status": "ongoing",
    "year": 2024,
    "img": null,
    "featured": false,
    "coordinates": [
      19.012,
      72.82
    ]
  },
  {
    "id": "lakhi-house",
    "title": "Lakhi House",
    "client": "Shree Somnathinfra Pvt Ltd.",
    "category": "residential",
    "location": "Mahalaxmi",
    "area": "5.5L Sq.ft",
    "status": "ongoing",
    "year": 2025,
    "img": null,
    "featured": true,
    "coordinates": [
      18.983,
      72.821
    ]
  },
  {
    "id": "balmoral-chembur",
    "title": "Balmoral",
    "client": "Rustomjee Group",
    "category": "residential",
    "location": "Chembur",
    "area": "13L Sq.ft",
    "status": "ongoing",
    "year": 2025,
    "img": "assets/Projects/balmoral.webp",
    "featured": true,
    "coordinates": [
      19.062,
      72.9004
    ]
  },
  {
    "id": "clif-tower",
    "title": "Clif Tower",
    "client": "Rustomjee Group",
    "category": "residential",
    "location": "Bandra",
    "area": "3.5L Sq.ft",
    "status": "ongoing",
    "year": 2026,
    "img": "assets/Projects/Cliff-Tower_Render.jpg",
    "featured": false,
    "coordinates": [
      19.054,
      72.83
    ]
  }
];
if (typeof window !== 'undefined') window.PROJECT_DATA = PROJECT_DATA;
