/**
 * STRONG BUILT · SCROLL REVEAL
 * ─────────────────────────────────────────────────────────────
 * One shared IntersectionObserver that drives `.md-reveal`
 * animations across every page. Replaces the per-page observers
 * that lived in index.html / projects.html / contact.html / etc.
 *
 * Usage:
 *   <div class="md-reveal">…</div>                   default fade-up
 *   <div class="md-reveal fade-left">…</div>          slide from left
 *   <div class="md-reveal scale-in d3">…</div>        scale-in with 240ms delay
 *   <ul class="md-reveal-stagger">                   children stagger
 *     <li>…</li><li>…</li><li>…</li>
 *   </ul>
 *
 * Plus auto-reveal: any <h1>, <h2>, .md-section-head, or any card
 * gets a subtle fade-up automatically — no class needed.
 *
 * Skips animation entirely if user has prefers-reduced-motion.
 * ─────────────────────────────────────────────────────────────
 */
(function () {
  'use strict';

  // Bail early on reduced-motion preference
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    document.querySelectorAll('.md-reveal').forEach(el => el.classList.add('is-visible'));
    return;
  }

  // Auto-tag elements that should have a default reveal (no class needed).
  // Skip elements inside the header, drawer, or footer (those animate
  // on their own / never re-render).
  function autoTag() {
    const skip = (el) => el.closest('header, footer, .md-drawer, .md-fab, .md-version-chip');
    const candidates = document.querySelectorAll(
      'section h1, section h2, .md-section-head, .md-card, .md-vcard, .md-stat, ' +
      '.md-active-card, .md-step, .tg-card, .cl-test, .ir-metric, .cs-metric, ' +
      '.cr-benefit, .pf-hero h1, .ct-hero h1, .st-hero h1, .cl-hero h1, ' +
      '.cs-hero h1, .cr-hero h1, .ir-hero h1, .rc-hero h1, .rs-hero h1, ' +
      '.cu-hero h1, .ld-hero h1'
    );
    candidates.forEach(el => {
      if (!el.classList.contains('md-reveal') && !skip(el)) {
        el.classList.add('md-reveal');
      }
    });
  }

  // Auto-stagger children of .md-reveal-stagger by setting --i
  function applyStaggerIndices() {
    document.querySelectorAll('.md-reveal-stagger').forEach(parent => {
      Array.from(parent.children).forEach((child, i) => {
        if (!child.style.getPropertyValue('--i')) {
          child.style.setProperty('--i', i);
        }
        child.classList.add('md-reveal');
      });
    });
  }

  function init() {
    autoTag();
    applyStaggerIndices();

    const targets = document.querySelectorAll('.md-reveal');
    if (!targets.length) return;

    // Don't double-observe elements that already became visible
    // (e.g. hero text revealed by per-page scripts on load).
    const observer = new IntersectionObserver((entries, obs) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          obs.unobserve(entry.target);
        }
      });
    }, {
      threshold: 0.12,
      rootMargin: '0px 0px -8% 0px',
    });

    targets.forEach(el => {
      // Skip elements already marked visible by other scripts
      if (el.classList.contains('is-visible')) return;
      observer.observe(el);
    });

    // Re-run for content injected after page load (e.g. project cards
    // generated by project-gallery.js, or items added by admin preview).
    const mutationObserver = new MutationObserver(muts => {
      let needsRescan = false;
      for (const m of muts) {
        for (const node of m.addedNodes) {
          if (node.nodeType !== 1) continue;
          if (node.matches?.('.md-reveal') || node.querySelector?.('.md-reveal')) {
            needsRescan = true;
            break;
          }
        }
        if (needsRescan) break;
      }
      if (needsRescan) {
        autoTag();
        applyStaggerIndices();
        document.querySelectorAll('.md-reveal:not(.is-visible)').forEach(el => {
          observer.observe(el);
        });
      }
    });
    mutationObserver.observe(document.body, { childList: true, subtree: true });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
