/**
 * Testimonials Data — generated by Admin Studio on 2026-04-30T08:38:05.539Z
 */
const TESTIMONIALS_DATA = [
  {
    "name": "Test ",
    "id": "test",
    "company": "test",
    "initials": "tt",
    "quote": "<p>test ho raha hai</p>"
  }
];
if (typeof window !== 'undefined') window.TESTIMONIALS_DATA = TESTIMONIALS_DATA;
